
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mio.typeSecure.compiler.parser;

import com.mio.typeSecure.compiler.lexer.TSLexer;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class TSParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return TSParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public TSParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public TSParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public TSParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\002\000\002\002\004\000\002\002\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\003\000\004\002\000\001\002\000\004\002\005\001" +
    "\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\003\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$TSParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$TSParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$TSParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public TSParser(TSLexer lexer){
        super(lexer);

    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$TSParser$actions {
  private final TSParser parser;

  /** Constructor */
  CUP$TSParser$actions(TSParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$TSParser$do_action_part00000000(
    int                        CUP$TSParser$act_num,
    java_cup.runtime.lr_parser CUP$TSParser$parser,
    java.util.Stack            CUP$TSParser$stack,
    int                        CUP$TSParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$TSParser$result;

      /* select the action based on the action number */
      switch (CUP$TSParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= main EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$TSParser$stack.elementAt(CUP$TSParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$TSParser$stack.elementAt(CUP$TSParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$TSParser$stack.elementAt(CUP$TSParser$top-1)).value;
		RESULT = start_val;
              CUP$TSParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$TSParser$stack.elementAt(CUP$TSParser$top-1)), ((java_cup.runtime.Symbol)CUP$TSParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$TSParser$parser.done_parsing();
          return CUP$TSParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // main ::= 
            {
              Object RESULT =null;

              CUP$TSParser$result = parser.getSymbolFactory().newSymbol("main",0, ((java_cup.runtime.Symbol)CUP$TSParser$stack.peek()), RESULT);
            }
          return CUP$TSParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$TSParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$TSParser$do_action(
    int                        CUP$TSParser$act_num,
    java_cup.runtime.lr_parser CUP$TSParser$parser,
    java.util.Stack            CUP$TSParser$stack,
    int                        CUP$TSParser$top)
    throws java.lang.Exception
    {
              return CUP$TSParser$do_action_part00000000(
                               CUP$TSParser$act_num,
                               CUP$TSParser$parser,
                               CUP$TSParser$stack,
                               CUP$TSParser$top);
    }
}

}
