
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mio.typeSecure.compiler.parser;

/** CUP generated class containing symbol constants. */
public class TSParserSym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int FLOOR = 65;
  public static final int BIGINT = 30;
  public static final int CONST = 35;
  public static final int STRING_VALUE = 72;
  public static final int LESS_EQ = 17;
  public static final int EXP = 64;
  public static final int SIN = 62;
  public static final int CONSOLE_LOG = 46;
  public static final int NUMBER_VALUE = 70;
  public static final int COMMA = 23;
  public static final int RBRACE = 26;
  public static final int RANDOM = 68;
  public static final int RPAREN = 10;
  public static final int POW = 66;
  public static final int INCREMENT = 2;
  public static final int GREATER_EQ = 16;
  public static final int CHAR_AT = 42;
  public static final int LBRACE = 25;
  public static final int LPAREN = 9;
  public static final int FALSE = 28;
  public static final int NOT = 15;
  public static final int CEIL = 60;
  public static final int LOWER = 43;
  public static final int STRING_FUN = 39;
  public static final int MOD = 8;
  public static final int TAN = 63;
  public static final int NUMBER = 29;
  public static final int TRUE = 27;
  public static final int PLUS = 4;
  public static final int DIVIDE = 7;
  public static final int NOT_EQUALS = 14;
  public static final int WHILE = 50;
  public static final int ASSIGN = 20;
  public static final int BOOLEAN = 32;
  public static final int BOOLEAN_FUN = 40;
  public static final int BIGINT_VALUE = 71;
  public static final int SYM = 73;
  public static final int DO = 51;
  public static final int FOR = 49;
  public static final int GREATER = 19;
  public static final int VOID = 33;
  public static final int RETURN = 55;
  public static final int CONCAT = 45;
  public static final int ELSE = 48;
  public static final int BREAK = 52;
  public static final int DOT = 24;
  public static final int NUMBER_FUN = 37;
  public static final int LENGTH = 41;
  public static final int SQRT_TWO = 58;
  public static final int PI = 57;
  public static final int UNDEFINED = 34;
  public static final int COS = 61;
  public static final int E = 56;
  public static final int EOF = 0;
  public static final int SEMICOLON = 12;
  public static final int BIGINT_FUN = 38;
  public static final int DECREMENT = 3;
  public static final int FUNCTION = 54;
  public static final int MINUS = 5;
  public static final int OR = 22;
  public static final int error = 1;
  public static final int CONTINUE = 53;
  public static final int IF = 47;
  public static final int ID = 69;
  public static final int ABS = 59;
  public static final int COLON = 11;
  public static final int SQRT = 67;
  public static final int STRING = 31;
  public static final int LESS = 18;
  public static final int UPPER = 44;
  public static final int AND = 21;
  public static final int LET = 36;
  public static final int EQUALS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INCREMENT",
  "DECREMENT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "LPAREN",
  "RPAREN",
  "COLON",
  "SEMICOLON",
  "EQUALS",
  "NOT_EQUALS",
  "NOT",
  "GREATER_EQ",
  "LESS_EQ",
  "LESS",
  "GREATER",
  "ASSIGN",
  "AND",
  "OR",
  "COMMA",
  "DOT",
  "LBRACE",
  "RBRACE",
  "TRUE",
  "FALSE",
  "NUMBER",
  "BIGINT",
  "STRING",
  "BOOLEAN",
  "VOID",
  "UNDEFINED",
  "CONST",
  "LET",
  "NUMBER_FUN",
  "BIGINT_FUN",
  "STRING_FUN",
  "BOOLEAN_FUN",
  "LENGTH",
  "CHAR_AT",
  "LOWER",
  "UPPER",
  "CONCAT",
  "CONSOLE_LOG",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "DO",
  "BREAK",
  "CONTINUE",
  "FUNCTION",
  "RETURN",
  "E",
  "PI",
  "SQRT_TWO",
  "ABS",
  "CEIL",
  "COS",
  "SIN",
  "TAN",
  "EXP",
  "FLOOR",
  "POW",
  "SQRT",
  "RANDOM",
  "ID",
  "NUMBER_VALUE",
  "BIGINT_VALUE",
  "STRING_VALUE",
  "SYM"
  };
}

